kubectl delete deployments --all
kubectl delete services --all
kubectl delete pods --all
kubectl delete pvc --all
kubectl delete pv --all
kubectl delete ingress --all
kubectl delete secret --all
kubectl delete configMap --all
kubectl delete httpRoute --all
kubectl delete gateway --all
